# Generated by Django 3.2.18 on 2023-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='email_is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('PH', 'phone'), ('EM', 'email')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
